data_params:
  pkl_path: 'data/deepcad_solid_deduplicated_id.pkl'
  latent_dir: 'vqvae/logs/recon/lightning_logs/version_0/pkl'
  max_bbox_num: 50

network_params:
  solid_model:
    type: 'SolidTransformer'
    bbox_embed_channels: null
    block_channels: [64, 128, 512]
    d_model: 512
  face_model:
    type: 'FaceTransformer'
    bbox_embed_channels: 512
    block_channels: [64, 128, 512]
    d_model: 512
  d_model: 512
  nhead: 16
  dim_feedforward: 1024
  dropout: 0.1

trainer_params:
  batch_size: 256
  lr: 0.0001
  weight_decay: 0.0
  lr_decay: 0.99
  accelerator: 'gpu'
  max_epochs: 3000
  devices: 1
  strategy: 'ddp'
  log_every_n_steps: 100
  gradient_clip_val: 1.0
  default_root_dir: 'face_solid/logs/debug'

  face_model:
    config_yaml: 'vqvae/logs/face/lightning_logs/version_1/config.yaml'
    checkpoint: 'vqvae/logs/face/lightning_logs/version_1/checkpoints/last.ckpt'
  solid_model:
    config_yaml: 'vqvae/logs/solid/lightning_logs/version_2/config.yaml'
    checkpoint: 'vqvae/logs/solid/lightning_logs/version_2/checkpoints/last.ckpt'
  mean_std_path: 'vqvae/logs/recon/lightning_logs/version_0/mean_std.pkl'




